module.exports = [
  {
    name:"NavItem1",
    link:"https://www.google.com"
  },
  {
    name:"NavItem2",
    link:"https://www.google.com"
  },
  {
    name:"NavItem3",
    link:"https://www.google.com"
  },
  {
    name:"NavItem4",
    link:"https://www.google.com"
  },
  {
    name:"NavItem5",
    link:"https://www.google.com"
  }
];
